### PR TITLE
Transition from consuming js-sdk source to `lib` (build output)

### LINKED ISSUE #3081: Cannot develop with linked matrix-js-sdk
### Steps to reproduce

1. Pull the latest version of `livekit`
2. `yarn install`
3. `yarn link matrix-js-sdk`
4. `yarn dev`
5. Open Element Call in a browser

#### What did you expect?

Element Call starts

#### What happened instead?

The page crashes on a white screen because there is a decorator used in matrix-js-sdk/src/http-api/fetch.ts, which Babel does not transpile. I thought https://stackoverflow.com/a/69665198 might be the solution here but it still doesn't transpile the decorator. (why?)

### Operating system

NixOS 24.11

### Browser information

Firefox 135.0.1

### URL for webapp

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by toger5**
Closes https://github.com/element-hq/element-call/issues/3081

As of https://github.com/element-hq/element-call/pull/3095 being merged, this allows us to switch between linked and unlinked copies of matrix-js-sdk while consuming its code in a uniform way (via the recommended `matrix-js-sdk/lib` build output).

### CODE REVIEW

File: src/useMatrixRTCSessionMemberships.ts [hunk 1]
```diff
@@ -5,12 +5,12 @@ SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
...
 
-import { logger } from "matrix-js-sdk/src/logger";
-import { type CallMembership } from "matrix-js-sdk/src/matrixrtc/CallMembership";
+import { logger } from "matrix-js-sdk/lib/logger";
+import { type CallMembership } from "matrix-js-sdk/lib/matrixrtc";
 import {
   type MatrixRTCSession,
   MatrixRTCSessionEvent,
-} from "matrix-js-sdk/src/matrixrtc/MatrixRTCSession";
+} from "matrix-js-sdk/lib/matrixrtc";
```
Comment (toger5) [inline src/useMatrixRTCSessionMemberships.ts]: here

File: src/utils/test.ts [hunk 2]
```diff
@@ -13,14 +13,14 @@ import {
...
+} from "matrix-js-sdk";
 import {
   CallMembership,
   type Focus,
   MatrixRTCSessionEvent,
   type MatrixRTCSessionEventHandlerMap,
   type SessionMembershipData,
-} from "matrix-js-sdk/src/matrixrtc";
+} from "matrix-js-sdk/lib/matrixrtc";
 import {
```
Comment (toger5) [inline src/utils/test.ts:24]: split this into type and normal imports?

File: src/tile/GridTile.test.tsx [hunk 3]
```diff
@@ -10,7 +10,7 @@ import { test, expect } from "vitest";
 import { render, screen } from "@testing-library/react";
 import { axe } from "vitest-axe";
 import { of } from "rxjs";
-import { type MatrixRTCSession } from "matrix-js-sdk/src/matrixrtc/MatrixRTCSession";
+import { type MatrixRTCSession } from "matrix-js-sdk/lib/matrixrtc";
```
Comment (toger5) [inline src/tile/GridTile.test.tsx:13]:
```suggestion
import type { MatrixRTCSession } from "matrix-js-sdk/lib/matrixrtc";
```

File: src/state/MediaViewModel.ts [hunk 4]
```diff
@@ -26,7 +26,7 @@ import {
   RoomEvent as LivekitRoomEvent,
   RemoteTrack,
 } from "livekit-client";
-import { type RoomMember } from "matrix-js-sdk/src/matrix";
+import { type RoomMember } from "matrix-js-sdk";
```
Comment (toger5) [inline src/state/MediaViewModel.ts:29]:
```suggestion
import type { RoomMember } from "matrix-js-sdk";
```

File: src/room/useLoadGroupCall.ts [hunk 5]
```diff
@@ -13,18 +13,20 @@ import {
...
   type RoomSummary,
-} from "matrix-js-sdk/src/client";
-import { SyncState } from "matrix-js-sdk/src/sync";
-import { type MatrixRTCSession } from "matrix-js-sdk/src/matrixrtc/MatrixRTCSession";
-import { RoomEvent, type Room } from "matrix-js-sdk/src/models/room";
-import { KnownMembership } from "matrix-js-sdk/src/types";
-import { JoinRule, MatrixError } from "matrix-js-sdk/src/matrix";
+  RoomEvent,
+  type Room,
+} from "matrix-js-sdk";
```
Comment (toger5) [inline src/room/useLoadGroupCall.ts:27]: large enought to split into `import type ...` and `import { no types`

File: src/room/RoomPage.tsx [hunk 6]
```diff
@@ -13,13 +13,13 @@ import {
   useRef,
   type JSX,
 } from "react";
-import { logger } from "matrix-js-sdk/src/logger";
+import { type MatrixError } from "matrix-js-sdk";
```
Comment (toger5) [inline src/room/RoomPage.tsx:16]:
```suggestion
import type { MatrixError } from "matrix-js-sdk";
```

File: src/room/LobbyView.tsx [hunk 7]
```diff
@@ -7,10 +7,10 @@ Please see LICENSE in the repository root for full details.
 
 import { type FC, useCallback, useMemo, useState, type JSX } from "react";
 import { useTranslation } from "react-i18next";
-import { type MatrixClient } from "matrix-js-sdk/src/matrix";
+import { type MatrixClient } from "matrix-js-sdk";
```
Comment (toger5) [inline src/room/LobbyView.tsx:10]:
```suggestion
import type { MatrixClient } from "matrix-js-sdk";
```

File: src/room/InviteModal.tsx [hunk 8]
```diff
@@ -13,7 +13,7 @@ import {
   useState,
 } from "react";
 import { useTranslation } from "react-i18next";
-import { type Room } from "matrix-js-sdk/src/matrix";
+import { type Room } from "matrix-js-sdk";
```
Comment (toger5) [inline src/room/InviteModal.tsx:16]:
```suggestion
import type { Room } from "matrix-js-sdk";
```

**Review by toger5 — COMMENTED** [review]
There a a couple more of these. Not sure its necassary and what the best practice is.

**Comment by robintown** [comment]
Regarding the type imports, we currently [have Eslint configured](https://github.com/element-hq/element-call/blob/21140f6f2c7ffb14d1d7237fc03f9fd66b5f611c/.eslintrc.cjs#L43) to always prefer putting the `type` keyword inline inside an import group, so I will refrain from changing that here. If you want to change the style I suggest you create a PR updating the lint config.

**Review by robintown — APPROVED** [review]
