### PR TITLE
Fix to-device encryption info label

### LINKED ISSUE #3201: The `using to Device key transport` label is shown when there is no to-device key sharing happening
The label at the top needs revisiting and more logic when it is shown. (now it just mirrors the setting and listens to the event that gets emitted when the fallback to room key happens)
The logic has to be:

- are we using perParticipantE2EE
- is the dev flag enabled
- are we still in to-device mode or already fallen back to room keys

### PR DESCRIPTION
**Pull request by toger5**
fixes: https://github.com/element-hq/element-call/issues/3201
The label was shown also without checking that we use PerParticipantE2EE. Which is a prerequisite for toDevice transport. As a result the label was shown when not desired.

### CODE REVIEW

File: src/room/InCallView.tsx [hunk 1]
```diff
@@ -220,19 +223,21 @@ export const InCallView: FC<InCallViewProps> = ({
...
-  );
-  useEffect(() => {
-    setShowToDeviceEncryption(toDeviceEncryptionSetting);
-  }, [toDeviceEncryptionSetting]);
+  const [didFallbackToRoomKey, setDidFallbackToRoomKey] = useState(false);
   useTypedEventEmitter(
     rtcSession,
     RoomAndToDeviceEvents.EnabledTransportsChanged,
-    (enabled) => setShowToDeviceEncryption(enabled.to_device),
+    (enabled) => setDidFallbackToRoomKey(enabled.room),
```
Comment (toger5) [inline src/room/InCallView.tsx:234]: This is the actual bug: I used `enabled.to_device` but of course `enabled.room` is better.

**Review by BillCarsonFr — APPROVED** [review]
we can't have a test?

**Comment by toger5** [comment]
@BillCarsonFr yes, I will add a test.
