### PR TITLE
Fix connection leaks: Ensure that any pending connection open are cancelled/undo when ActiveCall is unmounted

### LINKED ISSUE #3268: Potential race causing a re-connection to livekit after the component is unmounted.
### Steps to reproduce

1. Where are you starting? What can you see?

Some Rageshake stating that Oher members could still hear a user after he left.
https://github.com/element-hq/element-call-rageshakes/issues/10192

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #3268

### CODE REVIEW

File: src/livekit/useECConnectionState.ts [hunk 1]
```diff
@@ -59,7 +59,8 @@ async function doConnect(
   livekitRoom: Room,
   sfuConfig: SFUConfig,
   audioEnabled: boolean,
-  audioOptions: AudioCaptureOptions,
+  initialDeviceId: string | undefined,
+  cancellable: Cancellable,
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts]:
```suggestion
  cancelable: Cancelable,
```

Comment (toger5) [reply src/livekit/useECConnectionState.ts]: Is `abortHandle` a good name for this. `cancelable` sounds more like a bool flag?

File: src/livekit/useECConnectionState.ts [hunk 2]
```diff
@@ -82,19 +83,40 @@ async function doConnect(
...
     if (audioTracks.length < 1) {
       logger.info("Tried to pre-create local audio track but got no tracks");
     } else {
       preCreatedAudioTrack = audioTracks[0];
     }
+    // There was a yield point previously (awaiting for the track to be created) so we need to check
+    // if the operation was cancelled and stop connecting if needed.
+    if (cancellable.isCancelled()) {
+      logger.info(
+        "[Lifecycle] Signal Aborted: Pre-created audio track but connection aborted",
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts:98]: Can we use a logger child instead of a manual `[Lifecycle]` prefix?

File: src/livekit/useECConnectionState.ts [hunk 3]
```diff
@@ -247,6 +281,22 @@ export function useECConnectionState(
 
   const currentSFUConfig = useRef(Object.assign({}, sfuConfig));
 
+  // Protection against potential leaks, where the component to be unmounted and there is
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts:284]: "is about to be"?

File: src/livekit/useECConnectionState.ts [hunk 4]
```diff
@@ -247,6 +281,22 @@ export function useECConnectionState(
...
+  // still a pending doConnect promise. This would lead the user to still be in the call even
+  // if the component is unmounted.
+  const cancelBag = useRef(new Set<Cancellable>());
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts]: `abortHandles`?

File: src/livekit/useECConnectionState.ts [hunk 5]
```diff
@@ -273,11 +323,14 @@ export function useECConnectionState(
       // always capturing audio: it helps keep bluetooth headsets in the right mode and
       // mobile browsers to know we're doing a call.
       setIsInDoConnect(true);
+      const cancellable = new Cancellable();
+      cancelBag.current.add(cancellable);
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts]: Is there an assumption we can do about having only one doConnect running?
Can we enforce this somehow? This would allow us to not use a Set for the `Cancellable`s (`abortHandles`)

File: src/livekit/useLivekit.ts [hunk 6]
```diff
@@ -155,9 +155,7 @@ export function useLivekit(
   );
 
   const connectionState = useECConnectionState(
-    {
-      deviceId: initialDevices.current.audioInput.selectedId,
-    },
+    initialDevices.current.audioInput.selectedId,
```
Comment (toger5) [inline src/livekit/useLivekit.ts:158]: Really good that you detected and fixed this!

File: src/utils/cancellable.ts [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+  public constructor(private cancelled = false) {}
+
+  public cancel(): void {
+    this.cancelled = true;
+  }
+
+  public isCancelled(): boolean {
+    return this.cancelled;
+  }
+}
```
Comment (toger5) [inline src/utils/cancellable.ts]:
```suggestion
export class AbortHandle {
  public constructor(private aborted = false) {}

  public abort(): void {
    this.aborted = true;
  }

  public isAborted(): boolean {
    return this.aborted;
  }
}
```

File: src/livekit/useECConnectionState.ts [hunk 8]
```diff
@@ -247,6 +281,22 @@ export function useECConnectionState(
...
+  // This is a cleanup function that will be called when the component is unmounted.
+  // It will cancel all cancellables in the bag
+  useEffect(() => {
+    const bag = cancelBag.current;
+    return (): void => {
+      bag.forEach((cancellable) => {
+        cancellable.cancel();
+      });
+    };
+  }, []);
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts]:
```suggestion
  useEffect(() => () => {
      cancelBag.current.forEach((cancellable) => cancellable.cancel());
    };
  }, []);
```

**Review by toger5 — CHANGES_REQUESTED** [review]
Looking good.
I think renaming would make sense. (If cancellable is from "able to cancel" its spelled wrong?)

File: src/livekit/useECConnectionState.ts (hunk 8 above)
Comment (BillCarsonFr) [reply src/livekit/useECConnectionState.ts]: It is on purpose to avoid a warning. When using `cancelBag.current` , technically the `current`could have changed by the time the cleanup function is called. Not really relevant in our case given it is only set once. (TS30010: [react-hooks/exhaustive-deps]

File: src/livekit/useECConnectionState.ts [hunk 9]
```diff
@@ -284,15 +284,15 @@ export function useECConnectionState(
...
 
-  // This is a cleanup function that will be called when the component is unmounted.
-  // It will cancel all cancellables in the bag
+  // This is a cleanup function that will be called when the component is about to be unmounted.
+  // It will cancel all abortHandles in the bag
   useEffect(() => {
-    const bag = cancelBag.current;
+    const bag = abortHandlesBag.current;
     return (): void => {
       bag.forEach((cancellable) => {
```
Comment (toger5) [inline src/livekit/useECConnectionState.ts]: can we also rename the variable and property to `abortHandle`

File: src/livekit/useECConnectionState.ts (hunk 2 above)
Comment (toger5) [reply src/livekit/useECConnectionState.ts:98]: this seems to not have worked

**Review by toger5 — APPROVED** [review]
