### PR TITLE
Release preparations

### LINKED ISSUE #1189: Fix simulcast screen sharing
Screen-sharing does not work in Chrome.

### PR DESCRIPTION
**Pull request by daniel-abramov**
Minimal set of fixes for the #1165 and 30 fps screen-sharing.

Fixes screen-sharing in Chrome, but disables simulcast (tbd #1189).

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]

File: src/livekit/options.ts [hunk 1]
```diff
@@ -17,8 +17,9 @@ const defaultLiveKitPublishOptions: TrackPublishDefaults = {
   videoSimulcastLayers: [VideoPresets.h180, VideoPresets.h216] as VideoPreset[],
   screenShareEncoding: ScreenSharePresets.h1080fps30.encoding,
   screenShareSimulcastLayers: [
-    new VideoPreset(1920, 1080, 1_500_000, 5, "medium"),
+    new VideoPreset(1920, 1080, 500_000, 5, "medium"),
```
Comment (toger5) [inline src/livekit/options.ts]: is the screensharing fixed if we remote the 5fps layer entirely?

Comment (daniel-abramov) [reply src/livekit/options.ts]: Sadly it only gets fixed if we remove all simulcast layers. Apparently, temporal layers don't work in Chrome or something like this.

But I think I get your point :) I.e. it's better to have screen sharing working in both browsers rather than having one browser with screen sharing support and another without.

I've removed them and only left the 30fps preset for the screen-sharing encoding. Now it should work in both browsers in 30 fps mode (but without a simulcast).

Comment (toger5) [reply src/livekit/options.ts]: where is the change with the removed screen sharing layers?

Comment (daniel-abramov) [reply src/livekit/options.ts]: I've forgotten to push, done :)
