### PR TITLE
Firefox audio output issues fix

### LINKED ISSUE #1437: No AEC on Firefox?
### Steps to reproduce

We have observed that some users are causing echo because the browser does not appear to be doing AEC. The common denominator seems to be Firefox: switching to Chrome fixes the problem.

Is it possible AEC doesn't work on Firefox with e2ee enabled?

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by toger5**
In firefox it causes issue to do a manaul audio output selection. Thos happen when the settings modal is opend.
As a user this can be observed as: Pressing on settings => all other participants can hear an echo.
This pr tries to disable the minimum so that the issue does not occur anymore.

Fixes: #1437 And hopefully: #1438

### CODE REVIEW

**Comment by toger5** [comment]
tested on android chrome + FF macos.

File: src/livekit/MediaDevicesContext.tsx [hunk 1]
```diff
@@ -120,10 +123,17 @@ interface Props {
 }
 
 export const MediaDevicesProvider: FC<Props> = ({ children }) => {
-  // Counts the number of callers currently using device names
+  // Counts the number of callers currently using device names.
   const [numCallersUsingNames, setNumCallersUsingNames] = useState(0);
   const usingNames = numCallersUsingNames > 0;
 
+  // Use output device names for output devices on all platforms except FF.
```
Comment (dbkr) [inline src/livekit/MediaDevicesContext.tsx:130]: I'm not sure this comment is really telling me anything that isn't apparent from the next line: the main question would be 'why'?

**Review by dbkr — APPROVED** [review]
otherwise lgtm!

**Review by robintown — APPROVED** [review]
