### PR TITLE
Fix joining calls with no media permission

### LINKED ISSUE #1661: Auto mute my audio and video when I decline mic/camera permissions
#### What would you like to do?

For calls when I don't expect to speak, I usually deny permissions to microphone and camera. But Element Call still has me unmuted on the pre-call screen.

#### Why would you like to do it?

So I don't have to remember to mute my audio and video and enter the call with black video and appearing unmuted.

#### How would you like to achieve it?

Default me to muted on the pre-call screen after I decline mic/cam permissions.

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### LINKED ISSUE #1907: EC fails if denied media permissions
### Steps to reproduce

1. Try to join a call (in a fresh browser so you get media permission prompts)
2. Deny media perms

#### What did you expect?
To be able to join the the call & see/hear people but not unmute mic/camera

#### What happened instead?
Sat on "waiting for participants" forever

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by dbkr**
You can still try to unmute your media in the preview screen and the button will show unmuted, but then mute again once you actually join, so not 100% perfect but better.

Fixes https://github.com/vector-im/element-call/issues/1907
Fixes https://github.com/vector-im/element-call/issues/1661

### CODE REVIEW

File: src/livekit/useLiveKit.ts [hunk 1]
```diff
@@ -245,11 +245,25 @@ export function useLiveKit(
...
-              e,
-            );
-            setTimeout(() => syncMuteState(iterCount + 1, type), 1000);
+            if ((e as DOMException).name === "NotAllowedError") {
+              logger.error(
+                "Fatal errror while syncing mute state: resetting",
+                e,
+              );
+              if (type === MuteDevice.Microphone) {
+                audioMuteUpdating.current = false;
```
Comment (dbkr) [inline src/livekit/useLiveKit.ts:254]: We also forgot to clear this flag on an exception so it would never update the mute state at all after an error(!)

**Review by robintown — APPROVED** [review]

File: src/livekit/useLiveKit.ts (hunk 1 above)
Comment (robintown) [reply src/livekit/useLiveKit.ts:254]: Nice find
