### PR TITLE
Disable call button while the call is connecting.

### LINKED ISSUE #3530: The 'join' button appears to do nothing if the JWT check is delayed.
### Steps to reproduce

1. Start a video call in a room (embedded in EW/ED)
2. Hit the join button from the lobby
3. EC tries to authorise livekit to participate in the room via JWT stuff, which may take a while (e.g. if the matrixrtc auth service can't query synapse via the federation API, or takes a while for DNS to resolve, or whatever)
4. Nothing happens.
5. You keep hitting the join button.
6. Eventually it suddenly comes to life.

#### What did you expect?

The join button should be greyed out or show a spinner or something after you start the process of joining.

#### What happened instead?

There's no evidence anything is happening despite the delay; the app feels flakey

### Operating system

macOS

### Browser information

ED

### URL for webapp

Nightly

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes https://github.com/element-hq/element-call/issues/3530

### CODE REVIEW

**Review by toger5 — APPROVED** [review]
Thanks. This one seems super simple.

Does it make sense to port this one to the multi-sfu branch as well?

File: src/room/LobbyView.tsx [hunk 1]
```diff
@@ -193,6 +193,13 @@ export const LobbyView: FC<Props> = ({
 
   useTrackProcessorSync(videoTrack);
 
+  const onEnterCall = useCallback(() => {
+    setWaiting(true);
+    void onEnter().finally(() => setWaiting(false));
+  }, [onEnter]);
+
+  const [waiting, setWaiting] = useState(waitingForInvite);
```
Comment (robintown) [inline src/room/LobbyView.tsx]: I know that `waitingForInvite` never actually gets updated in practice without fully unmounting and remounting the lobby view, but just to avoid a future surprise: could we have this component react to its updates?

```suggestion
  const [waitingToEnter, setWaitingToEnter] = useState(false);
  const waiting = waitingForInvite || waitingToEnter;
```

**Review by robintown — CHANGES_REQUESTED** [review]

**Comment by robintown** [comment]
> Does it make sense to port this one to the multi-sfu branch as well?

Sure, I'll continue merging livekit → multi-sfu every now and then.

**Review by robintown — APPROVED** [review]
