### PR TITLE
Show speaking indicators in spotlight during screen sharing

### LINKED ISSUE #2689: Speaking indicators not shown when a screen share is in the spotlight
### Steps to reproduce

1. Share your screen
2. Go into spotlight

#### What did you expect?

When others speak, their tiles light up with speaking indicators

#### What happened instead?

No speaking indicators, because the idea was that in spotlight mode any speakers would get moved to the spotlight, so indicators are redundant. But that's not actually the case when there's a screen share.

### Operating system

NixOS unstable

### Browser information

Firefox 131.0.2

### URL for webapp

call.element.dev

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by robintown**
Closes https://github.com/element-hq/element-call/issues/2689

### CODE REVIEW

File: src/state/CallViewModel.ts [hunk 1]
```diff
@@ -714,7 +714,21 @@ export class CallViewModel extends ViewModel {
...
-    map((l) => l.type !== "one-on-one" && !l.type.startsWith("spotlight-")),
+    map((l) => {
+      switch (l.type) {
+        case "spotlight-landscape":
+        case "spotlight-portrait":
+          // If the spotlight is showing the active speaker, we can do without
+          // speaking indicators as they're a redundant visual cue. But if
+          // screen sharing feeds are in the spotlight we still need them.
+          return l.spotlight[0] instanceof ScreenShareViewModel;
+        case "spotlight-expanded":
```
Comment (hughns) [inline src/state/CallViewModel.ts:729]: Why is -expanded treated differently from -landscape/-portrait?

Comment (robintown) [reply src/state/CallViewModel.ts:729]: Added a comment

**Review by hughns — CHANGES_REQUESTED** [review]
Thank you. Looks good other than the lint error.

**Review by hughns — APPROVED** [review]
