### PR TITLE
Fix audio being muted when joining a call

### LINKED ISSUE #1221: When joining the call audio gets muted even if it was enabled in the lobby

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-call/issues/1221

cc @toger5

### CODE REVIEW

File: src/room/VideoPreview.tsx [hunk 1]
```diff
@@ -201,13 +192,13 @@ export function VideoPreview({ matrixInfo, onUserChoicesChanged }: Props) {
...
-            onPress={() => setAudioEnabled(!audioAvailableAndEndabled)}
+            muted={!audioAvailableAndEnabled}
+            onPress={() => setAudioEnabled(!audioAvailableAndEnabled)}
             disabled={!audioTrack}
           />
           <VideoButton
-            muted={!videoAvailableAndEndabled}
-            onPress={() => setVideoEnabled(!videoAvailableAndEndabled)}
+            muted={!videoAvailableAndEnabled}
+            onPress={() => setVideoEnabled(!videoAvailableAndEnabled)}
```
Comment (toger5) [inline src/room/VideoPreview.tsx:206]: oh,  thx for catching the typo here

File: src/room/VideoPreview.tsx [hunk 2]
```diff
@@ -149,19 +144,15 @@ export function VideoPreview({ matrixInfo, onUserChoicesChanged }: Props) {
         setInitializingVideo(false);
       }
       videoTrack?.getDeviceId().then((videoId) => {
-        if (videoId) {
-          videoIn.setSelected(videoId);
-        }
+        videoIn.setSelected(videoId ?? "default");
```
Comment (toger5) [inline src/room/VideoPreview.tsx:147]: I think a comment here could be helpful:
```
// getDeviceId can return undefined, for audio devices. This happens if the devices list uses "default" as the device id for the current device and the device set on the track also uses the deviceId "default". Check `normalizeDeviceId` in  `getDeviceId` for more details.

**Review by toger5 — APPROVED** [review]

**Review by toger5 — APPROVED** [review]
