### PR TITLE
Put the settings tabs back in the right order

### LINKED ISSUE #1256: Profile settings tab comes after 'more'
### Steps to reproduce

1. Open settings

#### What did you expect?

The order of the tabs should be: audio, video, profile, feedback, more

#### What happened instead?

The actual order right now is: audio, video, feedback, more, profile

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by robintown**
Closes https://github.com/vector-im/element-call/issues/1256

### CODE REVIEW

File: src/settings/SettingsModal.tsx [hunk 1]
```diff
@@ -188,73 +211,64 @@ export const SettingsModal = (props: Props) => {
...
-    );
-  }
+  const tabs = [
+    audioTab,
+    videoTab,
+    ...(isEmbedded ? [] : [profileTab]),
+    feedbackTab,
+    moreTab,
+    ...(developerSettingsTab ? [developerTab] : []),
+  ];
```
Comment (SimonBrandner) [inline src/settings/SettingsModal.tsx]: I think I'd prefer using `tabs.push()` the conditions here are somewhat weirdly written

**Review by SimonBrandner — APPROVED** [review]
