### PR TITLE
Fully remove walkie-talkie mode

### LINKED ISSUE #1341: Remove walkie talkie mode
### Your use case

...from the livekit branch, because it doesn't work with livekit.

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by robintown**
The landing pages now look like this:

Screenshot 2023-09-18 at 11-05-19 Element Call Home
Screenshot 2023-09-18 at 11-04-14 Element Call Home

Closes https://github.com/vector-im/element-call/issues/1341

### CODE REVIEW

File: src/home/RegisteredView.tsx [hunk 1]
```diff
@@ -129,14 +121,16 @@ export function RegisteredView({ client, isPasswordlessUser }: Props) {
...
+          </Heading>
           <Form className={styles.form} onSubmit={onSubmit}>
             <FieldRow className={styles.fieldRow}>
               <InputField
                 id="callName"
                 name="callName"
-                label={callNameLabel}
-                placeholder={callNameLabel}
+                label={t("Name of call")}
+                placeholder={t("Name of call")}
```
Comment (robintown) [inline src/home/RegisteredView.tsx:137]: I chose these strings, because they're what's used in the new designs

Comment (dbkr) [reply src/home/RegisteredView.tsx:137]: Also useful because this really is for starting calls now, not joining them.

**Review by dbkr — APPROVED** [review]
